name: Upstream Sync

permissions:
  contents: write
  pull-requests: write

on:
  schedule:
    - cron: "15 2 * * *"
  workflow_dispatch:
    inputs:
      upstream_branch:
        description: "上游仓库分支名"
        default: "main"
      target_branch:
        description: "目标分支名"
        default: "main"

jobs:
  sync_latest_from_upstream:
    name: Sync latest commits from upstream repo
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork }}

    steps:
      - name: Checkout target repo
        uses: actions/checkout@v3

      - name: Sync upstream changes
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          upstream_sync_repo: cmliu/CF-Workers-SUB
          upstream_sync_branch: ${{ github.event.inputs.upstream_branch || 'main' }}
          target_sync_branch: ${{ github.event.inputs.target_branch || 'main' }}
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          test_mode: false

      - name: Handle conflicts
        if: steps.sync.outcome == 'failure' && contains(steps.sync.output.message, 'conflict')
        run: |
          echo "冲突错误：请手动解决以下文件的冲突："
          git diff --name-only --diff-filter=U
          exit 1

      - name: Notify failure
        if: failure()
        uses: actions-slack/slack@v1
        with:
          status: failure
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
